// Devin "Lauren" Elder
// MIU Term 1301
// Project 2
// 01/10/2013

var json = {
	"contact1": {
		"userName": ["Username: ", "Snooky"],
		"age": ["Age: ", "28"],
		"city": ["City: ", "Lakeland"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2012-03-13"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Bisexual"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Dance"],
		"movie": ["Favorite Movie Genre: ", "Horror"],
		"compatible": ["Level of Compatibility: ", "5"],
		"notes": ["Additional Information: ", ""],
	},
	"contact2": {
		"userName": ["Username: ", "Jeff"],
		"age": ["Age: ", "25"],
		"city": ["City: ", "Auburndale"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2012-04-18"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Straight"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "No"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Rap"],
		"movie": ["Favorite Movie Genre: ", "Comedy"],
		"compatible": ["Level of Compatibility: ", "10"],
		"notes": ["Additional Information: ", ""],
	},
	"contact3": {
		"userName": ["Username: ", "Joseph"],
		"age": ["Age: ", "20"],
		"city": ["City: ", "Plant City"],
		"website": ["Dating Website: ", "Zoosk.com"],
		"contacted": ["First Contacted: ", "2012-11-12"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Straight"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "Yes"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Hip Hop"],
		"movie": ["Favorite Movie Genre: ", "Action"],
		"compatible": ["Level of Compatibility: ", "23"],
		"notes": ["Additional Information: ", ""],
	},
	"contact4": {
		"userName": ["Username: ", "Jessie"],
		"age": ["Age: ", "25"],
		"city": ["City: ", "Lakeland"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2011-04-24"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Bisexual"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "Yes"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "No"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Dance"],
		"movie": ["Favorite Movie Genre: ", "Drama"],
		"compatible": ["Level of Compatibility: ", "40"],
		"notes": ["Additional Information: ", ""],
	},
	"contact5": {
		"userName": ["Username: ", "FoodForThought"],
		"age": ["Age: ", "30"],
		"city": ["City: ", "Davenport"],
		"website": ["Dating Website: ", "Okcupid.com"],
		"contacted": ["First Contacted: ", "2012-07-04"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Science Fiction"],
		"compatible": ["Level of Compatibility: ", "55"],
		"notes": ["Additional Information: ", ""],
	},
	"contact6": {
		"userName": ["Username: ", "Dan"],
		"age": ["Age: ", "32"],
		"city": ["City: ", "Haines City"],
		"website": ["Dating Website: ", "Okcupid.com"],
		"contacted": ["First Contacted: ", "2012-08-12"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "Yes"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "No"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Rap"],
		"movie": ["Favorite Movie Genre: ", "Adventure"],
		"compatible": ["Level of Compatibility: ", "15"],
		"notes": ["Additional Information: ", ""],
	},
	"contact7": {
		"userName": ["Username: ", "Kays"],
		"age": ["Age: ", "28"],
		"city": ["City: ", "Mulberry"],
		"website": ["Dating Website: ", "Zoosk.com"],
		"contacted": ["First Contacted: ", "2012-03-17"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "No"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Pop"],
		"movie": ["Favorite Movie Genre: ", "Drama"],
		"compatible": ["Level of Compatibility: ", "5"],
		"notes": ["Additional Information: ", ""],
	},
	"contact8": {
		"userName": ["Username: ", "Tiffany"],
		"age": ["Age: ", "33"],
		"city": ["City: ", "Davenport"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2012-01-03"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "No"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Hip Hop"],
		"movie": ["Favorite Movie Genre: ", "Musical"],
		"compatible": ["Level of Compatibility: ", "2"],
		"notes": ["Additional Information: ", ""],
	},
	"contact9": {
		"userName": ["Username: ", "Barbara"],
		"age": ["Age: ", "38"],
		"city": ["City: ", "Winter Haven"],
		"website": ["Dating Website: ", "Zoosk.com"],
		"contacted": ["First Contacted: ", "2012-05-11"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Straight"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "No"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Drama"],
		"compatible": ["Level of Compatibility: ", "20"],
		"notes": ["Additional Information: ", ""],
	},
	"contact10": {
		"userName": ["Username: ", "Steve"],
		"age": ["Age: ", "29"],
		"city": ["City: ", "Winter Haven"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2010-12-07"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Straight"],
		"favorite": ["Favorite:", "Yes"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "Yes"],
		"stable": ["Is Financially Stable: ", "No"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Rock"],
		"movie": ["Favorite Movie Genre: ", "Horror"],
		"compatible": ["Level of Compatibility: ", "60"],
		"notes": ["Additional Information: ", ""],
	},
	"contact11": {
		"userName": ["Username: ", "Kathryn"],
		"age": ["Age: ", "30"],
		"city": ["City: ", "Plant City"],
		"website": ["Dating Website: ", "Zoosk.com"],
		"contacted": ["First Contacted: ", "2012-09-20"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Bisexual"],
		"favorite": ["Favorite:", "Yes"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "Yes"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "No"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "Yes"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Classical"],
		"movie": ["Favorite Movie Genre: ", "Science Fiction"],
		"compatible": ["Level of Compatibility: ", "70"],
		"notes": ["Additional Information: ", ""],
	},
	"contact12": {
		"userName": ["Username: ", "Tamsen"],
		"age": ["Age: ", "30"],
		"city": ["City: ", "Bartow"],
		"website": ["Dating Website: ", "Okcupid.com"],
		"contacted": ["First Contacted: ", "2012-04-14"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Straight"],
		"favorite": ["Favorite:", "Yes"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Action"],
		"compatible": ["Level of Compatibility: ", "35"],
		"notes": ["Additional Information: ", ""],
	},
	"contact13": {
		"userName": ["Username: ", "Brittany"],
		"age": ["Age: ", "24"],
		"city": ["City: ", "Auburndale"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2010-11-18"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Straight"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "No"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Pop"],
		"movie": ["Favorite Movie Genre: ", "Musical"],
		"compatible": ["Level of Compatibility: ", "2"],
		"notes": ["Additional Information: ", ""],
	},
	"contact14": {
		"userName": ["Username: ", "Vicki"],
		"age": ["Age: ", "29"],
		"city": ["City: ", "Lakeland"],
		"website": ["Dating Website: ", "Zoosk.com"],
		"contacted": ["First Contacted: ", "2012-10-31"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "No"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "Yes"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Drama"],
		"compatible": ["Level of Compatibility: ", "12"],
		"notes": ["Additional Information: ", ""],
	},
	"contact15": {
		"userName": ["Username: ", "Damon"],
		"age": ["Age: ", "36"],
		"city": ["City: ", "Winter Haven"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2011-05-18"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Bisexual"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "No"],
		"drinks": ["Drinks: ", "No"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Action"],
		"compatible": ["Level of Compatibility: ", "8"],
		"notes": ["Additional Information: ", ""],
	},
	"contact16": {
		"userName": ["Username: ", "Bede"],
		"age": ["Age: ", "33"],
		"city": ["City: ", "Auburndale"],
		"website": ["Dating Website: ", "Zoosk.com"],
		"contacted": ["First Contacted: ", "2011-02-13"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Comedy"],
		"compatible": ["Level of Compatibility: ", "29"],
		"notes": ["Additional Information: ", ""],
	},
	"contact17": {
		"userName": ["Username: ", "Todd"],
		"age": ["Age: ", "30"],
		"city": ["City: ", "Davenport"],
		"website": ["Dating Website: ", "Okcupid.com"],
		"contacted": ["First Contacted: ", "2012-06-01"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Blues"],
		"movie": ["Favorite Movie Genre: ", "Adventure"],
		"compatible": ["Level of Compatibility: ", "42"],
		"notes": ["Additional Information: ", ""],
	},
	"contact18": {
		"userName": ["Username: ", "Lance"],
		"age": ["Age: ", "34"],
		"city": ["City: ", "Winter Haven"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2011-07-06"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Drama"],
		"compatible": ["Level of Compatibility: ", "27"],
		"notes": ["Additional Information: ", ""],
	},
	"contact19": {
		"userName": ["Username: ", "Katrina"],
		"age": ["Age: ", "26"],
		"city": ["City: ", "Bradley"],
		"website": ["Dating Website: ", "Okcupid.com"],
		"contacted": ["First Contacted: ", "2012-09-18"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"favorite": ["Favorite:", "Yes"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "Yes"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "Yes"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Rock"],
		"movie": ["Favorite Movie Genre: ", "Science Fiction"],
		"compatible": ["Level of Compatibility: ", "98"],
		"notes": ["Additional Information: ", ""],
	},
	"contact20": {
		"userName": ["Username: ", "Sam"],
		"age": ["Age: ", "21"],
		"city": ["City: ", "Plant City"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "2010-03-14"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Straight"],
		"favorite": ["Favorite:", "No"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Adventure"],
		"compatible": ["Level of Compatibility: ", "13"],
		"notes": ["Additional Information: ", ""],
	}
}